### PR TITLE
htp/table: only fetch element when needed

### PR DESCRIPTION
**Pull request by inashivb**
Previous PR: https://github.com/OISF/libhtp/pull/432

Changes since v3:
- rebased on top of latest 0.5.x branch

### CODE REVIEW

**Comment by suricata-qa** [comment]
Information: QA ran without warnings. 

Pipeline 22122

**Comment by catenacyber** [comment]
Do you have some benchmark ?

The patch looks ok, but I am not sure it matters much...

**Comment by inashivb** [comment]
> Do you have some benchmark ?
> 
> The patch looks ok, but I am not sure it matters much...

No benchmarks w me. Feel free to reject it if it looks like noise. :)

**Review by victorjulien — APPROVED** [review]
Looks more efficient, so lets merge this.

**Comment by victorjulien** [comment]
Merged in #435, thanks!

**Pull request merged**
