### PR TITLE
response: fix RES_LINE body data handling - v2

### PR DESCRIPTION
**Pull request by cccs-sadugas**
See #362 for previous version.

### Changes since last version
* Test the data in each callback call separately.

### Testing/QA
I ran `make check` to make sure existing tests still pass.

The callback gets called once too many when running under valgrind. This is odd but some other tests also fail under valgrind on `0.5.x`.

### CODE REVIEW

**Comment by cccs-sadugas** [comment]
@catenacyber ready for another review.

**Review by catenacyber — APPROVED** [review]
Looks good to me cc @victorjulien

**Comment by catenacyber** [comment]
Thanks @cccs-sadugas for spotting and fixing this

**Comment by victorjulien** [comment]
Merged in #365, thanks!

**Pull request closed without merging**
