### PR TITLE
docs/: cleanup directory

### PR DESCRIPTION
**Pull request by aborrero**
Drop sources that aren't included in the suricata release tarball.
The most important removal is the docbook-xsl-ns-1.77.1 source, which
clearly doesn't belong here.

Signed-off-by: Arturo Borrero Gonzalez <arturo@debian.org>

### CODE REVIEW

**Comment by inliniac** [comment]
Why does this remove docs/COMPATIBILITY_CHANGES as well?

**Comment by aborrero** [comment]
> Why does this remove docs/COMPATIBILITY_CHANGES as well?

because it isn't included in the suricata tarball

**Comment by inliniac** [comment]
I think this file should be added to the dist then. Looks like other files in docs/ are in EXTRA_DIST in the 'root' Makefile.am

**Comment by aborrero** [comment]
Ok, resending PR

**Pull request closed without merging**
