### PR TITLE
util: better uint8_t typing

### PR DESCRIPTION
**Pull request by catenacyber**
cf https://redmine.openinfosecfoundation.org/issues/4516
cc @jlucovsky

### CODE REVIEW

**Comment by jlucovsky** [comment]
This looks good but it leaves a combination of `uint8_t` and `unsigned char` in use.  If the combination is intentional, then no change is needed. But, if `unsigned char` is used where a `uint8_t` is used, perhaps those could also be changed even if there are not any implicit size conversion issues?

**Comment by catenacyber** [comment]
> But, if unsigned char is used where a uint8_t is used, perhaps those could also be changed even if there are not any implicit size conversion issues?

I guess I prefer `uint8_t` but I do not know if there is a good reason... Maybe because the size is explicit...

**Comment by victorjulien** [comment]
> > But, if unsigned char is used where a uint8_t is used, perhaps those could also be changed even if there are not any implicit size conversion issues?
> 
> I guess I prefer `uint8_t` but I do not know if there is a good reason... Maybe because the size is explicit...

I definitely prefer explicit types over the older ones. So I'm all for replacing `unsigned char` with `uint8_t` and making similar conversions for other types.

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/libhtp/pull/339

**Pull request closed without merging**
