### PR TITLE
Accept responses without request

### PR DESCRIPTION
**Pull request by felix-jia**
This change is to support the async-oneside mode in Suricata. Under this mode, it is possible that responses do not match to any request, but these responses need to be inspected by Suricata.

This also answers the bug report for https://redmine.openinfosecfoundation.org/issues/993

### CODE REVIEW

**Comment by inliniac** [comment]
Wonder if it would make sense to use a more explicit URI. E.g. "/libhtp::request_uri_not_seen"
@b1v1r @wxsBSD any thoughts?

**Comment by wxsBSD** [comment]
I'm in favor of a more specific URI for sure. You can avoid the ugly snprintf with a static buffer by doing so. Why go with the timestamp?

**Comment by felix-jia** [comment]
Made the change to use a static URI.

Originally, was trying to differentiate these responses using timestamp for logging and debugging purposes. A static URI simplifies the code.

**Comment by victorjulien** [comment]
Merged this as part of #163, thanks a lot!

**Pull request closed without merging**
