### PR TITLE
next/254/20240120/v1

### PR DESCRIPTION
**Pull request by victorjulien**
Staging:
 - #399
 - #401
 - #412
 - #413

### CODE REVIEW

**Comment by victorjulien** [comment]
@catenacyber how will cifuzz become green again if this is merged?

**Comment by catenacyber** [comment]
> how will cifuzz become green again if this is merged?

Cifuzz is always green on the main branch, even if there are other known bugs (differential fuzzing findings) cf https://bugs.chromium.org/p/oss-fuzz/issues/list?q=label:Proj-libhtp

**Review by lukashino — APPROVED** [review]

**Comment by victorjulien** [comment]
PR not against up to date 0.5.x

**Comment by catenacyber** [comment]
> PR not against up to date 0.5.x

Should I do something ?

**Comment by victorjulien** [comment]
> > PR not against up to date 0.5.x
> 
> Should I do something ?

No, I need to rerun the staging but since we broken SV so we first need https://github.com/OISF/suricata-verify/pull/1601

**Pull request closed without merging**
