### PR TITLE
0.5.x: merge PRs

### PR DESCRIPTION
**Pull request by glongo**
This merges the following PRs:
- https://github.com/OISF/libhtp/pull/123
- https://github.com/OISF/libhtp/pull/125

### CODE REVIEW

**Comment by socketpair** [comment]
ping

**Comment by glongo** [comment]
Hello, the PR will be merged soon.
We need to run some QA on it.

**Comment by inliniac** [comment]
Could you update this to include #129 ?

**Comment by inliniac** [comment]
Add #122 while at it :)

**Pull request closed without merging**
