### PR TITLE
fix invalid unsigned arithmetic.

### PR DESCRIPTION
**Pull request by ihsinme**
I believe your checks are not correct.
in my opinion they are equivalent to checks !=.
I suggest a simple fix.

### CODE REVIEW

**Comment by catenacyber** [comment]
Thanks.
Do you have a test case to check that behavior is correct with this patch ?

**Comment by ihsinme** [comment]
no, I have no test to check.
I thought this was a very simple and straightforward fix.

if a test is needed give me an example.

**Comment by catenacyber** [comment]
The fix looks reasonable indeed.

But I would like to know how libhtp can now fail, and add a test to check that this does not happen again.

> if a test is needed give me an example.

You can look in the test directory.
You can for instance create a sample test file in test/files and use it in test/test_main.cpp

**Comment by ihsinme** [comment]
good day.
I'm sorry to be late with the reply.
After re-examining your code, I realized that your comparison will also work correctly.
since `endpos` can never be less than `startpos`.

**Pull request closed without merging**
