### PR TITLE
Adds travis builds with sanitizers support

### PR DESCRIPTION
**Pull request by catenacyber**
We could then add the whole generated fuzzing corpus to be tested (to test for regressions with new pull requests for instance)

### CODE REVIEW

**Comment by victorjulien** [comment]
Any idea on why the builds fail in travis?

**Comment by catenacyber** [comment]
Not really, I copied this from https://github.com/aquynh/capstone/blob/master/.travis.yml which I wrote

The problem seems to be with the use of c++ in the test directory
I will look into it later

**Comment by catenacyber** [comment]
It looks like travis is not using clang as a C++ compiler event though there is the compiler:clang option...

**Comment by catenacyber** [comment]
Ok, so indeed, it is because travis did not use clang++ as C++ compiler. This can at least be fixed by setting CXX environment variable

**Comment by catenacyber** [comment]
So here is a fix. I do not know if you have a better one so that travis and autotool configure agree on having clang++ as c++ compiler

**Comment by victorjulien** [comment]
Can you do a new PR with all commits squashed? Thanks!

**Pull request closed without merging**
