### PR TITLE
host: ipv6 address is a valid host

### PR DESCRIPTION
**Pull request by catenacyber**
Should I make a libhtp unit test for this ?

### CODE REVIEW

**Comment by catenacyber** [comment]
Makes https://github.com/OISF/suricata-verify/pull/520 pass

**Comment by catenacyber** [comment]
This comes from https://redmine.openinfosecfoundation.org/issues/3323
Should I make a specific ticket about this ?

**Comment by catenacyber** [comment]
https://redmine.openinfosecfoundation.org/issues/4666

**Comment by victorjulien** [comment]
Sadly this is not portable. FreeBSD, OpenBSD and Windows fail to build.

FreeBSD
```
htp_util.c:2453:18: error: invalid application of 'sizeof' to an incomplete type 'struct in6_addr'
        char dst[sizeof(struct in6_addr)];
                 ^     ~~~~~~~~~~~~~~~~~
htp_util.c:2453:32: note: forward declaration of 'struct in6_addr'
        char dst[sizeof(struct in6_addr)];
                               ^
htp_util.c:2457:26: error: use of undeclared identifier 'AF_INET6'
        return inet_pton(AF_INET6, str, dst);
                         ^
2 errors generated.
```

Windows (MinGW)
```
htp_util.c:44:10: fatal error: arpa/inet.h: No such file or directory
   44 | #include <arpa/inet.h>
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:593: htp_util.lo] Error 1
make[4]: *** Waiting for unfinished jobs....
```

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/libhtp/pull/332

It seems a matter on include files to get to `inet_pton` which can be found everywhere...
How can I test it with CI on multiple OSes ?

**Pull request closed without merging**
