### PR TITLE
Http1 removetx 5921 v10

### PR DESCRIPTION
**Pull request by catenacyber**
#416 with dummy debug commit

### CODE REVIEW

**Comment by victorjulien** [comment]
Is the failing test above already enough proof?

**Comment by catenacyber** [comment]
> Is the failing test above already enough proof?

Not yet, pushed another version passing tests

**Comment by victorjulien** [comment]
It aborts, but again only in the unix socket test.

**Comment by catenacyber** [comment]
Do you know which one of the 2 aborts ?

**Comment by catenacyber** [comment]
Does the unix socket test free transactions differently ?

Anyways, I think we should not get this optimization soon...

**Comment by victorjulien** [comment]
> Does the unix socket test free transactions differently ?

It shouldn't matter.
 
> Anyways, I think we should not get this optimization soon...

Agree. I will see if I can reproduce it manually after the releases next week.

**Comment by catenacyber** [comment]
> > Does the unix socket test free transactions differently ?
> 
> It shouldn't matter.
> 

Sure, just trying to understand the issue, to reproduce and fix it.
It seems to happen because transaction are not freed in order...

**Comment by catenacyber** [comment]
Replaced by https://github.com/OISF/libhtp/pull/418

**Pull request closed without merging**
